# coding: utf-8
from sqlalchemy import Column, Float, Index, MetaData, String, Table, Text
from sqlalchemy.dialects.mysql import BIGINT, INTEGER

metadata = MetaData()


t_ashareadjfactor = Table(
    'ashareadjfactor', metadata,
    Column('ts_code', String(9), index=True),
    Column('trade_date', String(8)),
    Column('adj_factor', Float(asdecimal=True)),
    Index('ashareadjfactor_trade_date_IDX', 'trade_date', 'ts_code', unique=True)
)


t_asharebalancesheet = Table(
    'asharebalancesheet', metadata,
    Column('ts_code', String(9)),
    Column('ann_date', String(8)),
    Column('f_ann_date', String(8)),
    Column('end_date', String(8)),
    Column('report_type', String(2)),
    Column('comp_type', String(1)),
    Column('end_type', String(1)),
    Column('total_share', Float(asdecimal=True)),
    Column('cap_rese', Float(asdecimal=True)),
    Column('undistr_porfit', Float(asdecimal=True)),
    Column('surplus_rese', Float(asdecimal=True)),
    Column('special_rese', Float(asdecimal=True)),
    Column('money_cap', Float(asdecimal=True)),
    Column('trad_asset', Float(asdecimal=True)),
    Column('notes_receiv', Float(asdecimal=True)),
    Column('accounts_receiv', Float(asdecimal=True)),
    Column('oth_receiv', Float(asdecimal=True)),
    Column('prepayment', Float(asdecimal=True)),
    Column('div_receiv', Float(asdecimal=True)),
    Column('int_receiv', Float(asdecimal=True)),
    Column('inventories', Float(asdecimal=True)),
    Column('amor_exp', Float(asdecimal=True)),
    Column('nca_within_1y', Float(asdecimal=True)),
    Column('sett_rsrv', Float(asdecimal=True)),
    Column('loanto_oth_bank_fi', Float(asdecimal=True)),
    Column('premium_receiv', Float(asdecimal=True)),
    Column('reinsur_receiv', Float(asdecimal=True)),
    Column('reinsur_res_receiv', Float(asdecimal=True)),
    Column('pur_resale_fa', Float(asdecimal=True)),
    Column('oth_cur_assets', Float(asdecimal=True)),
    Column('total_cur_assets', Float(asdecimal=True)),
    Column('fa_avail_for_sale', Float(asdecimal=True)),
    Column('htm_invest', Float(asdecimal=True)),
    Column('lt_eqt_invest', Float(asdecimal=True)),
    Column('invest_real_estate', Float(asdecimal=True)),
    Column('time_deposits', Float(asdecimal=True)),
    Column('oth_assets', Float(asdecimal=True)),
    Column('lt_rec', Float(asdecimal=True)),
    Column('fix_assets', Float(asdecimal=True)),
    Column('cip', Float(asdecimal=True)),
    Column('const_materials', Float(asdecimal=True)),
    Column('fixed_assets_disp', Float(asdecimal=True)),
    Column('produc_bio_assets', Float(asdecimal=True)),
    Column('oil_and_gas_assets', Float(asdecimal=True)),
    Column('intan_assets', Float(asdecimal=True)),
    Column('r_and_d', Float(asdecimal=True)),
    Column('goodwill', Float(asdecimal=True)),
    Column('lt_amor_exp', Float(asdecimal=True)),
    Column('defer_tax_assets', Float(asdecimal=True)),
    Column('decr_in_disbur', Float(asdecimal=True)),
    Column('oth_nca', Float(asdecimal=True)),
    Column('total_nca', Float(asdecimal=True)),
    Column('cash_reser_cb', Float(asdecimal=True)),
    Column('depos_in_oth_bfi', Float(asdecimal=True)),
    Column('prec_metals', Float(asdecimal=True)),
    Column('deriv_assets', Float(asdecimal=True)),
    Column('rr_reins_une_prem', Float(asdecimal=True)),
    Column('rr_reins_outstd_cla', Float(asdecimal=True)),
    Column('rr_reins_lins_liab', Float(asdecimal=True)),
    Column('rr_reins_lthins_liab', Float(asdecimal=True)),
    Column('refund_depos', Float(asdecimal=True)),
    Column('ph_pledge_loans', Float(asdecimal=True)),
    Column('refund_cap_depos', Float(asdecimal=True)),
    Column('indep_acct_assets', Float(asdecimal=True)),
    Column('client_depos', Float(asdecimal=True)),
    Column('client_prov', Float(asdecimal=True)),
    Column('transac_seat_fee', Float(asdecimal=True)),
    Column('invest_as_receiv', Float(asdecimal=True)),
    Column('total_assets', Float(asdecimal=True)),
    Column('lt_borr', Float(asdecimal=True)),
    Column('st_borr', Float(asdecimal=True)),
    Column('cb_borr', Float(asdecimal=True)),
    Column('depos_ib_deposits', Float(asdecimal=True)),
    Column('loan_oth_bank', Float(asdecimal=True)),
    Column('trading_fl', Float(asdecimal=True)),
    Column('notes_payable', Float(asdecimal=True)),
    Column('acct_payable', Float(asdecimal=True)),
    Column('adv_receipts', Float(asdecimal=True)),
    Column('sold_for_repur_fa', Float(asdecimal=True)),
    Column('comm_payable', Float(asdecimal=True)),
    Column('payroll_payable', Float(asdecimal=True)),
    Column('taxes_payable', Float(asdecimal=True)),
    Column('int_payable', Float(asdecimal=True)),
    Column('div_payable', Float(asdecimal=True)),
    Column('oth_payable', Float(asdecimal=True)),
    Column('acc_exp', Float(asdecimal=True)),
    Column('deferred_inc', Float(asdecimal=True)),
    Column('st_bonds_payable', Float(asdecimal=True)),
    Column('payable_to_reinsurer', Float(asdecimal=True)),
    Column('rsrv_insur_cont', Float(asdecimal=True)),
    Column('acting_trading_sec', Float(asdecimal=True)),
    Column('acting_uw_sec', Float(asdecimal=True)),
    Column('non_cur_liab_due_1y', Float(asdecimal=True)),
    Column('oth_cur_liab', Float(asdecimal=True)),
    Column('total_cur_liab', Float(asdecimal=True)),
    Column('bond_payable', Float(asdecimal=True)),
    Column('lt_payable', Float(asdecimal=True)),
    Column('specific_payables', Float(asdecimal=True)),
    Column('estimated_liab', Float(asdecimal=True)),
    Column('defer_tax_liab', Float(asdecimal=True)),
    Column('defer_inc_non_cur_liab', Float(asdecimal=True)),
    Column('oth_ncl', Float(asdecimal=True)),
    Column('total_ncl', Float(asdecimal=True)),
    Column('depos_oth_bfi', Float(asdecimal=True)),
    Column('deriv_liab', Float(asdecimal=True)),
    Column('depos', Float(asdecimal=True)),
    Column('agency_bus_liab', Float(asdecimal=True)),
    Column('oth_liab', Float(asdecimal=True)),
    Column('prem_receiv_adva', Float(asdecimal=True)),
    Column('depos_received', Float(asdecimal=True)),
    Column('ph_invest', Float(asdecimal=True)),
    Column('reser_une_prem', Float(asdecimal=True)),
    Column('reser_outstd_claims', Float(asdecimal=True)),
    Column('reser_lins_liab', Float(asdecimal=True)),
    Column('reser_lthins_liab', Float(asdecimal=True)),
    Column('indept_acc_liab', Float(asdecimal=True)),
    Column('pledge_borr', Float(asdecimal=True)),
    Column('indem_payable', Float(asdecimal=True)),
    Column('policy_div_payable', Float(asdecimal=True)),
    Column('total_liab', Float(asdecimal=True)),
    Column('treasury_share', Float(asdecimal=True)),
    Column('ordin_risk_reser', Float(asdecimal=True)),
    Column('forex_differ', Float(asdecimal=True)),
    Column('invest_loss_unconf', Float(asdecimal=True)),
    Column('minority_int', Float(asdecimal=True)),
    Column('total_hldr_eqy_exc_min_int', Float(asdecimal=True)),
    Column('total_hldr_eqy_inc_min_int', Float(asdecimal=True)),
    Column('total_liab_hldr_eqy', Float(asdecimal=True)),
    Column('lt_payroll_payable', Float(asdecimal=True)),
    Column('oth_comp_income', Float(asdecimal=True)),
    Column('oth_eqt_tools', Float(asdecimal=True)),
    Column('oth_eqt_tools_p_shr', Float(asdecimal=True)),
    Column('lending_funds', Float(asdecimal=True)),
    Column('acc_receivable', Float(asdecimal=True)),
    Column('st_fin_payable', Float(asdecimal=True)),
    Column('payables', Float(asdecimal=True)),
    Column('hfs_assets', Float(asdecimal=True)),
    Column('hfs_sales', Float(asdecimal=True)),
    Column('cost_fin_assets', Float(asdecimal=True)),
    Column('fair_value_fin_assets', Float(asdecimal=True)),
    Column('contract_assets', Float(asdecimal=True)),
    Column('contract_liab', Float(asdecimal=True)),
    Column('accounts_receiv_bill', Float(asdecimal=True)),
    Column('accounts_pay', Float(asdecimal=True)),
    Column('oth_rcv_total', Float(asdecimal=True)),
    Column('fix_assets_total', Float(asdecimal=True)),
    Column('cip_total', Float(asdecimal=True)),
    Column('oth_pay_total', Float(asdecimal=True)),
    Column('long_pay_total', Float(asdecimal=True)),
    Column('debt_invest', Float(asdecimal=True)),
    Column('oth_debt_invest', Float(asdecimal=True)),
    Column('oth_eq_invest', Float(asdecimal=True)),
    Column('oth_illiq_fin_assets', Float(asdecimal=True)),
    Column('oth_eq_ppbond', Float(asdecimal=True)),
    Column('receiv_financing', Float(asdecimal=True)),
    Column('use_right_assets', Float(asdecimal=True)),
    Column('lease_liab', Float(asdecimal=True)),
    Column('update_flag', String(1)),
    Index('asharebalancesheet_ts_code_IDX', 'ts_code', 'end_date', 'report_type', unique=True)
)


t_asharecalendar = Table(
    'asharecalendar', metadata,
    Column('tradedays', String(8), unique=True),
    Column('is_open', String(1))
)


t_asharecashflow = Table(
    'asharecashflow', metadata,
    Column('ts_code', String(9)),
    Column('ann_date', String(8)),
    Column('f_ann_date', String(8)),
    Column('end_date', String(8)),
    Column('comp_type', String(1)),
    Column('report_type', String(2)),
    Column('end_type', String(1)),
    Column('net_profit', Float(asdecimal=True)),
    Column('finan_exp', Float(asdecimal=True)),
    Column('c_fr_sale_sg', Float(asdecimal=True)),
    Column('recp_tax_rends', Float(asdecimal=True)),
    Column('n_depos_incr_fi', Float(asdecimal=True)),
    Column('n_incr_loans_cb', Float(asdecimal=True)),
    Column('n_inc_borr_oth_fi', Float(asdecimal=True)),
    Column('prem_fr_orig_contr', Float(asdecimal=True)),
    Column('n_incr_insured_dep', Float(asdecimal=True)),
    Column('n_reinsur_prem', Float(asdecimal=True)),
    Column('n_incr_disp_tfa', Float(asdecimal=True)),
    Column('ifc_cash_incr', Float(asdecimal=True)),
    Column('n_incr_disp_faas', Float(asdecimal=True)),
    Column('n_incr_loans_oth_bank', Float(asdecimal=True)),
    Column('n_cap_incr_repur', Float(asdecimal=True)),
    Column('c_fr_oth_operate_a', Float(asdecimal=True)),
    Column('c_inf_fr_operate_a', Float(asdecimal=True)),
    Column('c_paid_goods_s', Float(asdecimal=True)),
    Column('c_paid_to_for_empl', Float(asdecimal=True)),
    Column('c_paid_for_taxes', Float(asdecimal=True)),
    Column('n_incr_clt_loan_adv', Float(asdecimal=True)),
    Column('n_incr_dep_cbob', Float(asdecimal=True)),
    Column('c_pay_claims_orig_inco', Float(asdecimal=True)),
    Column('pay_handling_chrg', Float(asdecimal=True)),
    Column('pay_comm_insur_plcy', Float(asdecimal=True)),
    Column('oth_cash_pay_oper_act', Float(asdecimal=True)),
    Column('st_cash_out_act', Float(asdecimal=True)),
    Column('n_cashflow_act', Float(asdecimal=True)),
    Column('oth_recp_ral_inv_act', Float(asdecimal=True)),
    Column('c_disp_withdrwl_invest', Float(asdecimal=True)),
    Column('c_recp_return_invest', Float(asdecimal=True)),
    Column('n_recp_disp_fiolta', Float(asdecimal=True)),
    Column('n_recp_disp_sobu', Float(asdecimal=True)),
    Column('stot_inflows_inv_act', Float(asdecimal=True)),
    Column('c_pay_acq_const_fiolta', Float(asdecimal=True)),
    Column('c_paid_invest', Float(asdecimal=True)),
    Column('n_disp_subs_oth_biz', Float(asdecimal=True)),
    Column('oth_pay_ral_inv_act', Float(asdecimal=True)),
    Column('n_incr_pledge_loan', Float(asdecimal=True)),
    Column('stot_out_inv_act', Float(asdecimal=True)),
    Column('n_cashflow_inv_act', Float(asdecimal=True)),
    Column('c_recp_borrow', Float(asdecimal=True)),
    Column('proc_issue_bonds', Float(asdecimal=True)),
    Column('oth_cash_recp_ral_fnc_act', Float(asdecimal=True)),
    Column('stot_cash_in_fnc_act', Float(asdecimal=True)),
    Column('free_cashflow', Float(asdecimal=True)),
    Column('c_prepay_amt_borr', Float(asdecimal=True)),
    Column('c_pay_dist_dpcp_int_exp', Float(asdecimal=True)),
    Column('incl_dvd_profit_paid_sc_ms', Float(asdecimal=True)),
    Column('oth_cashpay_ral_fnc_act', Float(asdecimal=True)),
    Column('stot_cashout_fnc_act', Float(asdecimal=True)),
    Column('n_cash_flows_fnc_act', Float(asdecimal=True)),
    Column('eff_fx_flu_cash', Float(asdecimal=True)),
    Column('n_incr_cash_cash_equ', Float(asdecimal=True)),
    Column('c_cash_equ_beg_period', Float(asdecimal=True)),
    Column('c_cash_equ_end_period', Float(asdecimal=True)),
    Column('c_recp_cap_contrib', Float(asdecimal=True)),
    Column('incl_cash_rec_saims', Float(asdecimal=True)),
    Column('uncon_invest_loss', Float(asdecimal=True)),
    Column('prov_depr_assets', Float(asdecimal=True)),
    Column('depr_fa_coga_dpba', Float(asdecimal=True)),
    Column('amort_intang_assets', Float(asdecimal=True)),
    Column('lt_amort_deferred_exp', Float(asdecimal=True)),
    Column('decr_deferred_exp', Float(asdecimal=True)),
    Column('incr_acc_exp', Float(asdecimal=True)),
    Column('loss_disp_fiolta', Float(asdecimal=True)),
    Column('loss_scr_fa', Float(asdecimal=True)),
    Column('loss_fv_chg', Float(asdecimal=True)),
    Column('invest_loss', Float(asdecimal=True)),
    Column('decr_def_inc_tax_assets', Float(asdecimal=True)),
    Column('incr_def_inc_tax_liab', Float(asdecimal=True)),
    Column('decr_inventories', Float(asdecimal=True)),
    Column('decr_oper_payable', Float(asdecimal=True)),
    Column('incr_oper_payable', Float(asdecimal=True)),
    Column('others', Float(asdecimal=True)),
    Column('im_net_cashflow_oper_act', Float(asdecimal=True)),
    Column('conv_debt_into_cap', Float(asdecimal=True)),
    Column('conv_copbonds_due_within_1y', Float(asdecimal=True)),
    Column('fa_fnc_leases', Float(asdecimal=True)),
    Column('im_n_incr_cash_equ', Float(asdecimal=True)),
    Column('net_dism_capital_add', Float(asdecimal=True)),
    Column('net_cash_rece_sec', Float(asdecimal=True)),
    Column('credit_impa_loss', Float(asdecimal=True)),
    Column('use_right_asset_dep', Float(asdecimal=True)),
    Column('oth_loss_asset', Text),
    Column('end_bal_cash', Float(asdecimal=True)),
    Column('beg_bal_cash', Float(asdecimal=True)),
    Column('end_bal_cash_equ', Float(asdecimal=True)),
    Column('beg_bal_cash_equ', Float(asdecimal=True)),
    Column('update_flag', String(1)),
    Index('asharecashflow_ts_code_IDX', 'ts_code', 'end_date', 'report_type', unique=True)
)


t_ashareeodbasic = Table(
    'ashareeodbasic', metadata,
    Column('ts_code', String(9), index=True),
    Column('trade_date', String(8), index=True),
    Column('close', Float(asdecimal=True)),
    Column('turnover_rate', Float(asdecimal=True)),
    Column('turnover_rate_f', Float(asdecimal=True)),
    Column('volume_ratio', Float(asdecimal=True)),
    Column('pe', Float(asdecimal=True)),
    Column('pe_ttm', Float(asdecimal=True)),
    Column('pb', Float(asdecimal=True)),
    Column('ps', Float(asdecimal=True)),
    Column('ps_ttm', Float(asdecimal=True)),
    Column('dv_ratio', Float(asdecimal=True)),
    Column('dv_ttm', Float(asdecimal=True)),
    Column('total_share', Float(asdecimal=True)),
    Column('float_share', Float(asdecimal=True)),
    Column('free_share', Float(asdecimal=True)),
    Column('total_mv', Float(asdecimal=True)),
    Column('circ_mv', Float(asdecimal=True)),
    Index('AShareEodBasic_date_IDX', 'trade_date', 'ts_code', unique=True),
    comment='获取全部股票每日重要的基本面指标，可用于选股分析、报表展示等'
)


t_ashareeodprice = Table(
    'ashareeodprice', metadata,
    Column('ts_code', String(9), index=True),
    Column('trade_date', String(8)),
    Column('open', Float(asdecimal=True)),
    Column('high', Float(asdecimal=True)),
    Column('low', Float(asdecimal=True)),
    Column('close', Float(asdecimal=True)),
    Column('pre_close', Float(asdecimal=True)),
    Column('change', Float(asdecimal=True)),
    Column('pct_chg', Float(asdecimal=True)),
    Column('vol', Float(asdecimal=True)),
    Column('amount', Float(asdecimal=True)),
    Index('AShareEodPrice_date_IDX', 'trade_date', 'ts_code', unique=True)
)


t_ashareexpress = Table(
    'ashareexpress', metadata,
    Column('ts_code', String(9)),
    Column('ann_date', String(9)),
    Column('end_date', String(9)),
    Column('revenue', Float(asdecimal=True)),
    Column('operate_profit', Float(asdecimal=True)),
    Column('total_profit', Float(asdecimal=True)),
    Column('n_income', Float(asdecimal=True)),
    Column('total_assets', Float(asdecimal=True)),
    Column('total_hldr_eqy_exc_min_int', Float(asdecimal=True)),
    Column('diluted_eps', Float(asdecimal=True)),
    Column('diluted_roe', Float(asdecimal=True)),
    Column('yoy_net_profit', Float(asdecimal=True)),
    Column('bps', Float(asdecimal=True)),
    Column('yoy_sales', Float(asdecimal=True)),
    Column('yoy_op', Float(asdecimal=True)),
    Column('yoy_tp', Float(asdecimal=True)),
    Column('yoy_dedu_np', Float(asdecimal=True)),
    Column('yoy_eps', Float(asdecimal=True)),
    Column('yoy_roe', Float(asdecimal=True)),
    Column('growth_assets', Float(asdecimal=True)),
    Column('yoy_equity', Float(asdecimal=True)),
    Column('growth_bps', Float(asdecimal=True)),
    Column('or_last_year', Float(asdecimal=True)),
    Column('op_last_year', Float(asdecimal=True)),
    Column('tp_last_year', Float(asdecimal=True)),
    Column('np_last_year', Float(asdecimal=True)),
    Column('eps_last_year', Float(asdecimal=True)),
    Column('open_net_assets', Float(asdecimal=True)),
    Column('open_bps', Float(asdecimal=True)),
    Column('perf_summary', Text),
    Column('is_audit', BIGINT(20)),
    Column('remark', Text)
)


t_asharefinaindicator = Table(
    'asharefinaindicator', metadata,
    Column('ts_code', String(9)),
    Column('ann_date', String(8)),
    Column('end_date', String(8)),
    Column('eps', Float(asdecimal=True)),
    Column('dt_eps', Float(asdecimal=True)),
    Column('total_revenue_ps', Float(asdecimal=True)),
    Column('revenue_ps', Float(asdecimal=True)),
    Column('capital_rese_ps', Float(asdecimal=True)),
    Column('surplus_rese_ps', Float(asdecimal=True)),
    Column('undist_profit_ps', Float(asdecimal=True)),
    Column('extra_item', Float(asdecimal=True)),
    Column('profit_dedt', Float(asdecimal=True)),
    Column('gross_margin', Float(asdecimal=True)),
    Column('current_ratio', Float(asdecimal=True)),
    Column('quick_ratio', Float(asdecimal=True)),
    Column('cash_ratio', Float(asdecimal=True)),
    Column('invturn_days', Float(asdecimal=True)),
    Column('arturn_days', Float(asdecimal=True)),
    Column('inv_turn', Float(asdecimal=True)),
    Column('ar_turn', Float(asdecimal=True)),
    Column('ca_turn', Float(asdecimal=True)),
    Column('fa_turn', Float(asdecimal=True)),
    Column('assets_turn', Float(asdecimal=True)),
    Column('op_income', Float(asdecimal=True)),
    Column('valuechange_income', Float(asdecimal=True)),
    Column('interst_income', Float(asdecimal=True)),
    Column('daa', Float(asdecimal=True)),
    Column('ebit', Float(asdecimal=True)),
    Column('ebitda', Float(asdecimal=True)),
    Column('fcff', Float(asdecimal=True)),
    Column('fcfe', Float(asdecimal=True)),
    Column('current_exint', Float(asdecimal=True)),
    Column('noncurrent_exint', Float(asdecimal=True)),
    Column('interestdebt', Float(asdecimal=True)),
    Column('netdebt', Float(asdecimal=True)),
    Column('tangible_asset', Float(asdecimal=True)),
    Column('working_capital', Float(asdecimal=True)),
    Column('networking_capital', Float(asdecimal=True)),
    Column('invest_capital', Float(asdecimal=True)),
    Column('retained_earnings', Float(asdecimal=True)),
    Column('diluted2_eps', Float(asdecimal=True)),
    Column('bps', Float(asdecimal=True)),
    Column('ocfps', Float(asdecimal=True)),
    Column('retainedps', Float(asdecimal=True)),
    Column('cfps', Float(asdecimal=True)),
    Column('ebit_ps', Float(asdecimal=True)),
    Column('fcff_ps', Float(asdecimal=True)),
    Column('fcfe_ps', Float(asdecimal=True)),
    Column('netprofit_margin', Float(asdecimal=True)),
    Column('grossprofit_margin', Float(asdecimal=True)),
    Column('cogs_of_sales', Float(asdecimal=True)),
    Column('expense_of_sales', Float(asdecimal=True)),
    Column('profit_to_gr', Float(asdecimal=True)),
    Column('saleexp_to_gr', Float(asdecimal=True)),
    Column('adminexp_of_gr', Float(asdecimal=True)),
    Column('finaexp_of_gr', Float(asdecimal=True)),
    Column('impai_ttm', Float(asdecimal=True)),
    Column('gc_of_gr', Float(asdecimal=True)),
    Column('op_of_gr', Float(asdecimal=True)),
    Column('ebit_of_gr', Float(asdecimal=True)),
    Column('roe', Float(asdecimal=True)),
    Column('roe_waa', Float(asdecimal=True)),
    Column('roe_dt', Float(asdecimal=True)),
    Column('roa', Float(asdecimal=True)),
    Column('npta', Float(asdecimal=True)),
    Column('roic', Float(asdecimal=True)),
    Column('roe_yearly', Float(asdecimal=True)),
    Column('roa2_yearly', Float(asdecimal=True)),
    Column('roe_avg', Float(asdecimal=True)),
    Column('opincome_of_ebt', Float(asdecimal=True)),
    Column('investincome_of_ebt', Float(asdecimal=True)),
    Column('n_op_profit_of_ebt', Float(asdecimal=True)),
    Column('tax_to_ebt', Float(asdecimal=True)),
    Column('dtprofit_to_profit', Float(asdecimal=True)),
    Column('salescash_to_or', Float(asdecimal=True)),
    Column('ocf_to_or', Float(asdecimal=True)),
    Column('ocf_to_opincome', Float(asdecimal=True)),
    Column('capitalized_to_da', Float(asdecimal=True)),
    Column('debt_to_assets', Float(asdecimal=True)),
    Column('assets_to_eqt', Float(asdecimal=True)),
    Column('dp_assets_to_eqt', Float(asdecimal=True)),
    Column('ca_to_assets', Float(asdecimal=True)),
    Column('nca_to_assets', Float(asdecimal=True)),
    Column('tbassets_to_totalassets', Float(asdecimal=True)),
    Column('int_to_talcap', Float(asdecimal=True)),
    Column('eqt_to_talcapital', Float(asdecimal=True)),
    Column('currentdebt_to_debt', Float(asdecimal=True)),
    Column('longdeb_to_debt', Float(asdecimal=True)),
    Column('ocf_to_shortdebt', Float(asdecimal=True)),
    Column('debt_to_eqt', Float(asdecimal=True)),
    Column('eqt_to_debt', Float(asdecimal=True)),
    Column('eqt_to_interestdebt', Float(asdecimal=True)),
    Column('tangibleasset_to_debt', Float(asdecimal=True)),
    Column('tangasset_to_intdebt', Float(asdecimal=True)),
    Column('tangibleasset_to_netdebt', Float(asdecimal=True)),
    Column('ocf_to_debt', Float(asdecimal=True)),
    Column('ocf_to_interestdebt', Float(asdecimal=True)),
    Column('ocf_to_netdebt', Float(asdecimal=True)),
    Column('ebit_to_interest', Float(asdecimal=True)),
    Column('longdebt_to_workingcapital', Float(asdecimal=True)),
    Column('ebitda_to_debt', Float(asdecimal=True)),
    Column('turn_days', Float(asdecimal=True)),
    Column('roa_yearly', Float(asdecimal=True)),
    Column('roa_dp', Float(asdecimal=True)),
    Column('fixed_assets', Float(asdecimal=True)),
    Column('profit_prefin_exp', Float(asdecimal=True)),
    Column('non_op_profit', Float(asdecimal=True)),
    Column('op_to_ebt', Float(asdecimal=True)),
    Column('nop_to_ebt', Float(asdecimal=True)),
    Column('ocf_to_profit', Float(asdecimal=True)),
    Column('cash_to_liqdebt', Float(asdecimal=True)),
    Column('cash_to_liqdebt_withinterest', Float(asdecimal=True)),
    Column('op_to_liqdebt', Float(asdecimal=True)),
    Column('op_to_debt', Float(asdecimal=True)),
    Column('roic_yearly', Float(asdecimal=True)),
    Column('total_fa_trun', Float(asdecimal=True)),
    Column('profit_to_op', Float(asdecimal=True)),
    Column('q_opincome', Float(asdecimal=True)),
    Column('q_investincome', Float(asdecimal=True)),
    Column('q_dtprofit', Float(asdecimal=True)),
    Column('q_eps', Float(asdecimal=True)),
    Column('q_netprofit_margin', Float(asdecimal=True)),
    Column('q_gsprofit_margin', Float(asdecimal=True)),
    Column('q_exp_to_sales', Float(asdecimal=True)),
    Column('q_profit_to_gr', Float(asdecimal=True)),
    Column('q_saleexp_to_gr', Float(asdecimal=True)),
    Column('q_adminexp_to_gr', Float(asdecimal=True)),
    Column('q_finaexp_to_gr', Float(asdecimal=True)),
    Column('q_impair_to_gr_ttm', Float(asdecimal=True)),
    Column('q_gc_to_gr', Float(asdecimal=True)),
    Column('q_op_to_gr', Float(asdecimal=True)),
    Column('q_roe', Float(asdecimal=True)),
    Column('q_dt_roe', Float(asdecimal=True)),
    Column('q_npta', Float(asdecimal=True)),
    Column('q_opincome_to_ebt', Float(asdecimal=True)),
    Column('q_investincome_to_ebt', Float(asdecimal=True)),
    Column('q_dtprofit_to_profit', Float(asdecimal=True)),
    Column('q_salescash_to_or', Float(asdecimal=True)),
    Column('q_ocf_to_sales', Float(asdecimal=True)),
    Column('q_ocf_to_or', Float(asdecimal=True)),
    Column('basic_eps_yoy', Float(asdecimal=True)),
    Column('dt_eps_yoy', Float(asdecimal=True)),
    Column('cfps_yoy', Float(asdecimal=True)),
    Column('op_yoy', Float(asdecimal=True)),
    Column('ebt_yoy', Float(asdecimal=True)),
    Column('netprofit_yoy', Float(asdecimal=True)),
    Column('dt_netprofit_yoy', Float(asdecimal=True)),
    Column('ocf_yoy', Float(asdecimal=True)),
    Column('roe_yoy', Float(asdecimal=True)),
    Column('bps_yoy', Float(asdecimal=True)),
    Column('assets_yoy', Float(asdecimal=True)),
    Column('eqt_yoy', Float(asdecimal=True)),
    Column('tr_yoy', Float(asdecimal=True)),
    Column('or_yoy', Float(asdecimal=True)),
    Column('q_gr_yoy', Float(asdecimal=True)),
    Column('q_gr_qoq', Float(asdecimal=True)),
    Column('q_sales_yoy', Float(asdecimal=True)),
    Column('q_sales_qoq', Float(asdecimal=True)),
    Column('q_op_yoy', Float(asdecimal=True)),
    Column('q_op_qoq', Float(asdecimal=True)),
    Column('q_profit_yoy', Float(asdecimal=True)),
    Column('q_profit_qoq', Float(asdecimal=True)),
    Column('q_netprofit_yoy', Float(asdecimal=True)),
    Column('q_netprofit_qoq', Float(asdecimal=True)),
    Column('equity_yoy', Float(asdecimal=True)),
    Column('rd_exp', Float(asdecimal=True)),
    Column('update_flag', String(1)),
    Index('asharefinaindicator_ts_code_end_IDX', 'ts_code', 'end_date', unique=True)
)


t_ashareincome = Table(
    'ashareincome', metadata,
    Column('ts_code', String(9)),
    Column('ann_date', String(8)),
    Column('f_ann_date', String(8)),
    Column('end_date', String(8)),
    Column('report_type', String(2)),
    Column('comp_type', String(1)),
    Column('end_type', String(1)),
    Column('basic_eps', Float(asdecimal=True)),
    Column('diluted_eps', Float(asdecimal=True)),
    Column('total_revenue', Float(asdecimal=True)),
    Column('revenue', Float(asdecimal=True)),
    Column('int_income', Float(asdecimal=True)),
    Column('prem_earned', Float(asdecimal=True)),
    Column('comm_income', Float(asdecimal=True)),
    Column('n_commis_income', Float(asdecimal=True)),
    Column('n_oth_income', Float(asdecimal=True)),
    Column('n_oth_b_income', Float(asdecimal=True)),
    Column('prem_income', Float(asdecimal=True)),
    Column('out_prem', Float(asdecimal=True)),
    Column('une_prem_reser', Float(asdecimal=True)),
    Column('reins_income', Float(asdecimal=True)),
    Column('n_sec_tb_income', Float(asdecimal=True)),
    Column('n_sec_uw_income', Float(asdecimal=True)),
    Column('n_asset_mg_income', Float(asdecimal=True)),
    Column('oth_b_income', Float(asdecimal=True)),
    Column('fv_value_chg_gain', Float(asdecimal=True)),
    Column('invest_income', Float(asdecimal=True)),
    Column('ass_invest_income', Float(asdecimal=True)),
    Column('forex_gain', Float(asdecimal=True)),
    Column('total_cogs', Float(asdecimal=True)),
    Column('oper_cost', Float(asdecimal=True)),
    Column('int_exp', Float(asdecimal=True)),
    Column('comm_exp', Float(asdecimal=True)),
    Column('biz_tax_surchg', Float(asdecimal=True)),
    Column('sell_exp', Float(asdecimal=True)),
    Column('admin_exp', Float(asdecimal=True)),
    Column('fin_exp', Float(asdecimal=True)),
    Column('assets_impair_loss', Float(asdecimal=True)),
    Column('prem_refund', Float(asdecimal=True)),
    Column('compens_payout', Float(asdecimal=True)),
    Column('reser_insur_liab', Float(asdecimal=True)),
    Column('div_payt', Float(asdecimal=True)),
    Column('reins_exp', Float(asdecimal=True)),
    Column('oper_exp', Float(asdecimal=True)),
    Column('compens_payout_refu', Float(asdecimal=True)),
    Column('insur_reser_refu', Float(asdecimal=True)),
    Column('reins_cost_refund', Float(asdecimal=True)),
    Column('other_bus_cost', Float(asdecimal=True)),
    Column('operate_profit', Float(asdecimal=True)),
    Column('non_oper_income', Float(asdecimal=True)),
    Column('non_oper_exp', Float(asdecimal=True)),
    Column('nca_disploss', Float(asdecimal=True)),
    Column('total_profit', Float(asdecimal=True)),
    Column('income_tax', Float(asdecimal=True)),
    Column('n_income', Float(asdecimal=True)),
    Column('n_income_attr_p', Float(asdecimal=True)),
    Column('minority_gain', Float(asdecimal=True)),
    Column('oth_compr_income', Float(asdecimal=True)),
    Column('t_compr_income', Float(asdecimal=True)),
    Column('compr_inc_attr_p', Float(asdecimal=True)),
    Column('compr_inc_attr_m_s', Float(asdecimal=True)),
    Column('ebit', Float(asdecimal=True)),
    Column('ebitda', Float(asdecimal=True)),
    Column('insurance_exp', Float(asdecimal=True)),
    Column('undist_profit', Float(asdecimal=True)),
    Column('distable_profit', Float(asdecimal=True)),
    Column('rd_exp', Float(asdecimal=True)),
    Column('fin_exp_int_exp', Float(asdecimal=True)),
    Column('fin_exp_int_inc', Float(asdecimal=True)),
    Column('transfer_surplus_rese', Float(asdecimal=True)),
    Column('transfer_housing_imprest', Float(asdecimal=True)),
    Column('transfer_oth', Float(asdecimal=True)),
    Column('adj_lossgain', Float(asdecimal=True)),
    Column('withdra_legal_surplus', Float(asdecimal=True)),
    Column('withdra_legal_pubfund', Float(asdecimal=True)),
    Column('withdra_biz_devfund', Float(asdecimal=True)),
    Column('withdra_rese_fund', Float(asdecimal=True)),
    Column('withdra_oth_ersu', Float(asdecimal=True)),
    Column('workers_welfare', Float(asdecimal=True)),
    Column('distr_profit_shrhder', Float(asdecimal=True)),
    Column('prfshare_payable_dvd', Float(asdecimal=True)),
    Column('comshare_payable_dvd', Float(asdecimal=True)),
    Column('capit_comstock_div', Float(asdecimal=True)),
    Column('net_after_nr_lp_correct', Float(asdecimal=True)),
    Column('oth_income', Float(asdecimal=True)),
    Column('asset_disp_income', Float(asdecimal=True)),
    Column('continued_net_profit', Float(asdecimal=True)),
    Column('end_net_profit', Float(asdecimal=True)),
    Column('credit_impa_loss', Float(asdecimal=True)),
    Column('net_expo_hedging_benefits', Float(asdecimal=True)),
    Column('oth_impair_loss_assets', Float(asdecimal=True)),
    Column('total_opcost', Float(asdecimal=True)),
    Column('amodcost_fin_assets', Float(asdecimal=True)),
    Column('update_flag', String(1)),
    Index('ashareincome_ts_code_IDX', 'ts_code', 'end_date', 'report_type', unique=True)
)


t_ashareindexeod = Table(
    'ashareindexeod', metadata,
    Column('ts_code', String(9)),
    Column('trade_date', String(9)),
    Column('close', Float(asdecimal=True)),
    Column('open', Float(asdecimal=True)),
    Column('high', Float(asdecimal=True)),
    Column('low', Float(asdecimal=True)),
    Column('pre_close', Float(asdecimal=True)),
    Column('change', Float(asdecimal=True)),
    Column('pct_chg', Float(asdecimal=True)),
    Column('vol', Float(asdecimal=True)),
    Column('amount', Float(asdecimal=True)),
    Index('ashareindexeod_ts_code_IDX', 'ts_code', 'trade_date', unique=True)
)


t_asharelimitlist = Table(
    'asharelimitlist', metadata,
    Column('trade_date', String(8)),
    Column('ts_code', String(9)),
    Column('name', String(7)),
    Column('close', Float(asdecimal=True)),
    Column('pct_chg', Float(asdecimal=True)),
    Column('amp', Float(asdecimal=True)),
    Column('fc_ratio', Float(asdecimal=True)),
    Column('fl_ratio', Float(asdecimal=True)),
    Column('fd_amount', Float(asdecimal=True)),
    Column('first_time', String(8)),
    Column('last_time', String(8)),
    Column('open_times', INTEGER(11)),
    Column('strth', Float(asdecimal=True)),
    Column('limit', String(1)),
    Index('asharelimitlist_trade_date_IDX', 'trade_date', 'ts_code', unique=True)
)


t_asharemoneyflow = Table(
    'asharemoneyflow', metadata,
    Column('ts_code', String(9), index=True),
    Column('trade_date', String(8)),
    Column('buy_sm_vol', INTEGER(11)),
    Column('buy_sm_amount', Float(asdecimal=True)),
    Column('sell_sm_vol', INTEGER(11)),
    Column('sell_sm_amount', Float(asdecimal=True)),
    Column('buy_md_vol', INTEGER(11)),
    Column('buy_md_amount', Float(asdecimal=True)),
    Column('sell_md_vol', INTEGER(11)),
    Column('sell_md_amount', Float(asdecimal=True)),
    Column('buy_lg_vol', INTEGER(11)),
    Column('buy_lg_amount', Float(asdecimal=True)),
    Column('sell_lg_vol', INTEGER(11)),
    Column('sell_lg_amount', Float(asdecimal=True)),
    Column('buy_elg_vol', INTEGER(11)),
    Column('buy_elg_amount', Float(asdecimal=True)),
    Column('sell_elg_vol', INTEGER(11)),
    Column('sell_elg_amount', Float(asdecimal=True)),
    Column('net_mf_vol', INTEGER(11)),
    Column('net_mf_amount', Float(asdecimal=True)),
    Index('asharemoneyflow_code_date_IDX', 'trade_date', 'ts_code', unique=True)
)


t_asharemutualfundbasic = Table(
    'asharemutualfundbasic', metadata,
    Column('ts_code', String(20)),
    Column('name', String(128)),
    Column('management', String(128)),
    Column('custodian', String(128)),
    Column('fund_type', String(20)),
    Column('found_date', String(8)),
    Column('due_date', String(8)),
    Column('list_date', String(8)),
    Column('issue_date', String(8)),
    Column('delist_date', String(8)),
    Column('issue_amount', Float(asdecimal=True)),
    Column('m_fee', Float(asdecimal=True)),
    Column('c_fee', Float(asdecimal=True)),
    Column('duration_year', Float(asdecimal=True)),
    Column('p_value', Float(asdecimal=True)),
    Column('min_amount', Float(asdecimal=True)),
    Column('exp_return', Float(asdecimal=True)),
    Column('benchmark', String(512)),
    Column('status', String(1)),
    Column('invest_type', String(20)),
    Column('type', String(20)),
    Column('trustee', String(128)),
    Column('purc_startdate', String(8)),
    Column('redm_startdate', String(8)),
    Column('market', String(1))
)


t_asharemutualfunddaily = Table(
    'asharemutualfunddaily', metadata,
    Column('ts_code', String(20), index=True),
    Column('trade_date', String(8)),
    Column('pre_close', Float(asdecimal=True)),
    Column('open', Float(asdecimal=True)),
    Column('high', Float(asdecimal=True)),
    Column('low', Float(asdecimal=True)),
    Column('close', Float(asdecimal=True)),
    Column('change', Float(asdecimal=True)),
    Column('pct_chg', Float(asdecimal=True)),
    Column('vol', Float(asdecimal=True)),
    Column('amount', Float(asdecimal=True)),
    Index('asharemutualfunddaily_code_date_IDX', 'trade_date', 'ts_code', unique=True)
)


t_asharemutualfundnav = Table(
    'asharemutualfundnav', metadata,
    Column('ts_code', String(20), index=True),
    Column('ann_date', String(8)),
    Column('nav_date', String(8)),
    Column('unit_nav', Float(asdecimal=True)),
    Column('accum_nav', Float(asdecimal=True)),
    Column('accum_div', Float(asdecimal=True)),
    Column('net_asset', Float(asdecimal=True)),
    Column('total_netasset', Float(asdecimal=True)),
    Column('adj_nav', Float(asdecimal=True)),
    Column('update_flag', String(1)),
    Index('asharemutualfundnav_code_date_IDX', 'nav_date', 'ts_code')
)


t_asharesuspend = Table(
    'asharesuspend', metadata,
    Column('ts_code', String(9)),
    Column('trade_date', String(8)),
    Column('suspend_timing', String(12)),
    Column('suspend_type', String(1)),
    Index('asharesuspend_ts_code_IDX', 'ts_code', 'trade_date')
)


t_hs300_const = Table(
    'hs300_const', metadata,
    Column('index_code', String(9)),
    Column('con_code', String(9)),
    Column('trade_date', String(8)),
    Column('weight', Float(asdecimal=True))
)


t_month_map = Table(
    'month_map', metadata,
    Column('calendar_date', String(8)),
    Column('trade_date', String(8))
)


t_mutualfundadjfactor = Table(
    'mutualfundadjfactor', metadata,
    Column('ts_code', String(9)),
    Column('trade_date', String(8)),
    Column('adj_factor', Float(asdecimal=True))
)


t_stock_basic = Table(
    'stock_basic', metadata,
    Column('ts_code', String(9), index=True),
    Column('name', String(12)),
    Column('symbol', String(12)),
    Column('area', String(12)),
    Column('industry', String(12)),
    Column('list_date', String(8)),
    Column('delist_date', String(8)),
    Column('market', String(8)),
    Column('exchange', String(8)),
    Column('list_status', String(8)),
    Column('is_hs', String(8)),
    Column('act_ent_type', String(8))
)


t_stock_history_name = Table(
    'stock_history_name', metadata,
    Column('ts_code', String(9)),
    Column('name', String(12)),
    Column('start_date', String(8)),
    Column('end_date', String(8)),
    Column('ann_date', String(8)),
    Column('change_reason', String(10))
)


t_sw_industry = Table(
    'sw_industry', metadata,
    Column('stock_code', String(9)),
    Column('class_code', String(9)),
    Column('trade_date', String(8), index=True)
)


t_sw_industry_classify_lv1 = Table(
    'sw_industry_classify_lv1', metadata,
    Column('index_code', String(9)),
    Column('industry_name', String(9)),
    Column('level_name', String(2)),
    Column('industry_code', String(6)),
    Column('is_pub', String(1)),
    Column('parent_code', String(6)),
    Column('src', String(6))
)


t_sw_industry_classify_lv2 = Table(
    'sw_industry_classify_lv2', metadata,
    Column('index_code', String(9)),
    Column('industry_name', String(9)),
    Column('level_name', String(2)),
    Column('industry_code', String(6)),
    Column('is_pub', String(1)),
    Column('parent_code', String(6)),
    Column('src', String(6))
)


t_sw_industry_classify_lv3 = Table(
    'sw_industry_classify_lv3', metadata,
    Column('index_code', String(9)),
    Column('industry_name', String(9)),
    Column('level_name', String(2)),
    Column('industry_code', String(6)),
    Column('is_pub', String(1)),
    Column('parent_code', String(6)),
    Column('src', String(6))
)


t_sw_industry_lv2 = Table(
    'sw_industry_lv2', metadata,
    Column('stock_code', String(9)),
    Column('class_code', String(9)),
    Column('trade_date', String(8))
)


t_ths_index_basic = Table(
    'ths_index_basic', metadata,
    Column('ts_code', String(9), nullable=False),
    Column('name', String(12)),
    Column('count', Float(asdecimal=True)),
    Column('exchange', String(2)),
    Column('list_date', String(8)),
    Column('type', String(1))
)


t_ths_index_daily = Table(
    'ths_index_daily', metadata,
    Column('ts_code', String(9), nullable=False),
    Column('trade_date', String(8), nullable=False),
    Column('close', Float(asdecimal=True)),
    Column('open', Float(asdecimal=True)),
    Column('high', Float(asdecimal=True)),
    Column('low', Float(asdecimal=True)),
    Column('pre_close', Float(asdecimal=True)),
    Column('avg_price', Float(asdecimal=True)),
    Column('change', Float),
    Column('pct_change', Float(asdecimal=True)),
    Column('vol', Float(asdecimal=True)),
    Column('turnover_rate', Float)
)


t_ths_member = Table(
    'ths_member', metadata,
    Column('ts_code', String(9), nullable=False),
    Column('code', String(9), nullable=False),
    Column('name', String(6)),
    Column('create_time', String(20), nullable=False)
)


t_trade_days_begin_end_of_month = Table(
    'trade_days_begin_end_of_month', metadata,
    Column('month_start', String(8)),
    Column('month_end', String(8))
)


t_zz500_const = Table(
    'zz500_const', metadata,
    Column('index_code', String(9)),
    Column('con_code', String(9)),
    Column('trade_date', String(8)),
    Column('weight', Float(asdecimal=True))
)
